name: flutter_jailbreak_detection
description: Flutter jailbreak and root detection plugin. This plugin wraps Rootbeer for use on Android and DTTJailbreakDetection for use on iOS. 
version: 1.7.1
homepage: https://github.com/jeroentrappers/flutter_jailbreak_detection

environment:
  sdk: ">=3.4.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: appmire.be.flutterjailbreakdetection
        pluginClass: FlutterJailbreakDetectionPlugin
      ios:
        pluginClass: FlutterJailbreakDetectionPlugin
